module.exports =  {
	"Atlanta United": "https://www.atlutd.com/players",
	"Chicago Fire": "http://www.chicago-fire.com/players",
	"Colorado Rapids": "http://www.coloradorapids.com/players",
	"Columbus Crew": "http://www.columbuscrewsc.com/players",
	"DC United": "http://www.dcunited.com/players",
	"FC Dallas": "http://www.fcdallas.com/players",
	"Houston Dynamo": "http://www.houstondynamo.com/players",
	"LAFC": "https://www.lafc.com/players",
	"LA Galaxy": "http://www.lagalaxy.com/players",
	"Minnesota United": "https://www.mnufc.com/players",
	"Montreal Impact": "http://www.impactmontreal.com/players",
	"New England Revolution": "http://www.revolutionsoccer.net/players",
	"NYCFC": "http://www.nycfc.com/players",
	"New York Red Bulls": "http://www.newyorkredbulls.com/players",
	"Orlando City SC": "http://www.orlandocitysc.com/players",
	"Philadelpia Union": "http://www.philadelphiaunion.com/players",
	"Portland Timbers": "http://www.timbers.com/players",
	"Real Salt Lake": "http://www.realsaltlake.com/players",
	"San Jose Earthquakes": "http://www.sjearthquakes.com/players",
	"Seattle Sounders": "http://www.soundersfc.com/players",
	"Sporting KC": "http://www.sportingkc.com/players",
	"Toronto FC": "http://www.torontofc.ca/players",
	"Vancouver Whitecaps": "http://www.whitecapsfc.com/players"
};